# Rake tasks for currencies fixtures management.
namespace :money do
  $KCODE = 'UTF8'
  yaml_file = "#{File.dirname(__FILE__)}/../../lib/fixtures/currencies.yml"
  ruby_file = "#{File.dirname(__FILE__)}/../../lib/money/currencies.rb"

  desc "Generate currencies.rb file from currencies.yml"
  task :generate do
    require 'yaml'
    write_rb(symbolized_keys(parse_yaml(yaml_file)), ruby_file)
  end

  desc "dump currencies.rb file to lib/fixtures/currencies.yml"
  task :dump do
    require 'ya2yaml' # Needed for full UTF-8 support
    require 'money'
    write_yaml(stringify_keys(Money::Currency::TABLE), yaml_file)
  end
end

private

def stringify_keys(hash)
  hash.each do |key,val|
    hash[key.to_s] = hash.delete(key)
    val.each { |ke,va| val[ke.to_s] = val.delete(ke) }
  end
  hash
end

def symbolized_keys(hash)
  hash.each do |key,val|
    hash[key.to_sym] = hash.delete(key)
    val.each { |ke,va| val[ke.to_sym] = val.delete(ke) }
  end
  hash
end

def write_yaml(hash, file)
  File.open(file, 'w') do |f|
    f.write(hash.ya2yaml(
    :hash_order           => %w(priority iso_code name symbol subunit subunit_to_unit symbol_first html_entity decimal_mark thousands_separator),
    :escape_as_utf8       => false
    ))
  end
end

def parse_yaml(file)
  YAML.load_file(file)
end

def write_rb(hash, file)
  table = hash.collect  do |key,val|
    ":#{key} => #{val.inspect}"
  end.join(",\n")

  File.open(file, 'w') do |f|
    f.write("# Generated file, on #{Time.now}.  Do not edit this file, but lib/fixtures/currencies.yml instead. and run rake money:generate.\n")
    f.write("class Money\n")
    f.write(" class Currency\n")
    f.write(" TABLE = {\n")
    f.write(table)
    f.write("\n } #end of Hash\n")
    f.write(" end\n")
    f.write("end\n")
  end
end

