class Money
  module Constructors
    # Creates a new Money object with value 0.
    #
    # @param [Currency, String, Symbol] currency The currency to use.
    #
    # @return [Money]
    #
    # @example
    #   Money.empty #=> #<Money @fractional=0>
    def empty: (?(Money::Currency | string | Symbol) currency) -> Money

    alias zero empty

    # Creates a new Money object of value given in the +unit+ of the given
    # +currency+.
    #
    # @param [Numeric] amount The numerical value of the money.
    # @param [Currency, String, Symbol] currency The currency format.
    # @param [Hash] options Optional settings for the new Money instance
    # @option [Money::Bank::*] :bank The exchange bank to use.
    #
    # @example
    #   Money.from_amount(23.45, "USD") # => #<Money fractional:2345 currency:USD>
    #   Money.from_amount(23.45, "JPY") # => #<Money fractional:23 currency:JPY>
    #
    # @return [Money]
    #
    # @see #initialize
    def from_amount: (Numeric amount, ?(Money::Currency | string | Symbol) currency, ?::Hash[untyped, untyped] options) -> Money

    # DEPRECATED.
    #
    # @see Money.from_amount
    def from_dollars: (Numeric amount, ?(Money::Currency | string | Symbol) currency, ?::Hash[untyped, untyped] options) -> Money
  end
end
